name: GitHub-Profile-Summary-Cards

on:
  schedule:
    - cron: "0 0 * * *" # Se ejecuta cada 24h
  workflow_dispatch: # Permite darle al botón manual

jobs:
  build:
    runs-on: ubuntu-latest
    name: generate-github-profile-summary-cards
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4
      
      - uses: vn7n24fzkq/github-profile-summary-cards@release
        env:
          GITHUB_TOKEN: ${{ secrets.PROFILE_TOKEN }}
        with:
          USERNAME: ${{ github.repository_owner }}
